### ISSUE TITLE
Error when exporting module profile

### ISSUE THREAD

**Issue by gravagehulk** [NateHawk85/module-profiles#15]
DnD - 1.6.1
Foundry - Version 9, Build 269

When I try to export my module profile, nothing happens. Here's the error from the console:

![image](https://user-images.githubusercontent.com/69117052/169043723-63cd708a-4347-4641-8777-1eace198344b.png)

**Comment by NateHawk85** [comment]
Hi gravagehulk. Thanks for the report, and sorry to hear you're running into this.

Could you provide a little more info, or submit a new issue with the Bug template [here](https://github.com/NateHawk85/module-profiles/issues/new/choose)? I tested a fresh installation of the newest version, and I couldn't replicate the issue on the native Foundry application, nor could I do it on Microsoft Edge. What OS/browser are you using?

Thank you so much in advance!

**Comment by gravagehulk** [comment]
I have never used the module before. I just installed it TODAY and enabled it in my world. So, from that perspective it is a fresh install. Short of a conflict with another module (like TinyUI), I can't imagine what else it would be.

I am using the Chromium version of Edge. 101.0.1210.47 This is the Arm version for Mac OS, but I doubt that is the issue.

**Comment by gravagehulk** [comment]
That seemed to work! I got a message that the profile had been copied to clipboard.

**Comment by NateHawk85** [comment]
Sweet! Glad to hear it, thanks for letting me know :) I went ahead and made this change a full release, so in a few minutes, you should be able to update to the newest release version. If that doesn't work for whatever reason (newest version should be v1.0.4), you can un-install/re-install the traditional way in the "Install Module" window.
