### ISSUE TITLE
[Bug]: Can't update (invalid manifest file)

### ISSUE THREAD

**Issue by Jonwh25** [NateHawk85/module-profiles#17]
### Describe the Bug

When updating I'm seeing 

![image](https://user-images.githubusercontent.com/60674327/169587224-90d0f3a5-e847-4a0a-bc5c-b4715a2d595f.png)

### Steps to Replicate

```bash
1) Click update
```

### Desired Outcome

It updates or confirms you are at the latest version

### Actual Outcome

N/A

### Foundry Version

9.269

### System and Version

D&D5e 1.6.1

### Module Profiles Version

1.0.4

### What browser did you see this on?

Chrome

### What OS were you using?

Win 10

### Installed Modules + Additional Info

N/A

**Comment by NateHawk85** [comment]
Thanks for the heads up! Unfortunately, our internet has been down for the past few days, but once it comes back up, I'll take a look at this. But at a glance, I think I see what the problem is with it.

**Comment by NateHawk85** [comment]
I created a [release](https://github.com/NateHawk85/module-profiles/releases/tag/v1.0.5) for this issue. However, there can be some instances where your module is unable to update accordingly. If you run into that, go ahead and uninstall/reinstall the module, and it should get you the most up-to-date version!
