### ISSUE TITLE
[Enhancement]:  Is Foundry v11 support planned?

### ISSUE THREAD

**Issue by devteamplus** [NateHawk85/module-profiles#28]
### Is your feature request related to a problem?

no

### Have you looked for an existing solution or alternative, and does one exist?

Yes

### Describe the enhancement!

Just curious if you're planning on supporting v11?  I find this module very helpful.

Thanks.

**Comment by mechanoid23** [comment]
Bump.

**Comment by NateHawk85** [comment]
Sorry about the delayed response, a release was just published for v11! Let me know if there are any breaking changes, but from my usage, everything looked like it worked well.
