### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cadowtin** [NateHawk85/module-profiles#3]
### Describe the Bug

No Module URL for the Module.json

### Steps to Replicate

```bash
1) Go to... module install
2) Click on... the module to try and install it
3) Scroll to...
```

### Desired Outcome

It to download the module

### Actual Outcome

It doesn't download it and errors

### Foundry Version

9.269

### System and Version

DND 5e 1.5.7

### Module Profiles Version

1.0.0

### What browser did you see this on?

Chrome

### Installed Modules

- Module Profiles v1.0.0

**Comment by NateHawk85** [comment]
Interesting. Thank you for the heads up, working on resolving this now!
